-- MySQL Script generated by MySQL Workbench
-- 06/05/16 16:23:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

--SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
--SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
--SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RWS
-- -----------------------------------------------------
-- 
-- 
DROP SCHEMA IF EXISTS RWS ;

-- -----------------------------------------------------
-- Schema RWS
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS RWS ;


CREATE TABLE RWS.administrateur (
                id_administrateur VARCHAR NOT NULL,
                nom_administrateur VARCHAR NOT NULL,
                niveau_admin VARCHAR NOT NULL,
                CONSTRAINT id_administrateur PRIMARY KEY (id_administrateur)
);


CREATE TABLE RWS.pays (
                id_pays VARCHAR NOT NULL,
                nom_pays VARCHAR NOT NULL,
                CONSTRAINT id_pays PRIMARY KEY (id_pays)
);


CREATE TABLE RWS.departement (
                id_departement VARCHAR NOT NULL,
                id_pays VARCHAR NOT NULL,
                nom_departement VARCHAR NOT NULL,
                CONSTRAINT id_departement PRIMARY KEY (id_departement)
);


CREATE TABLE RWS.ville (
                id_ville VARCHAR NOT NULL,
                nom_ville VARCHAR NOT NULL,
                code_postal VARCHAR NOT NULL,
                id_departement VARCHAR NOT NULL,
                CONSTRAINT id_ville PRIMARY KEY (id_ville)
);


CREATE TABLE RWS.utilisateur (
                id_ville VARCHAR NOT NULL,
                id_utilisateur VARCHAR NOT NULL,
                nom_utilisateur VARCHAR NOT NULL,
                prenom_utilisateur VARCHAR NOT NULL,
                date_nais_utilisateur DATE NOT NULL,
                mail_utilisateur VARCHAR NOT NULL,
                adresse_utilisateur VARCHAR NOT NULL,
                CONSTRAINT id_utilisateur PRIMARY KEY (id_ville)
);


CREATE TABLE RWS.style_musicale (
                id_style_musical VARCHAR NOT NULL,
                libelle_style_musical VARCHAR NOT NULL,
                CONSTRAINT id_style_musicale PRIMARY KEY (id_style_musical)
);


CREATE TABLE RWS.star (
                id_star VARCHAR NOT NULL,
                id_style_musical VARCHAR NOT NULL,
                nom_star VARCHAR NOT NULL,
                prenom_star VARCHAR NOT NULL,
                nom_artiste VARCHAR NOT NULL,
                telephone_star VARCHAR NOT NULL,
                CONSTRAINT id_star PRIMARY KEY (id_star)
);


CREATE TABLE RWS.evenement (
                id_evenement VARCHAR NOT NULL,
                id_ville VARCHAR NOT NULL,
                id_star VARCHAR NOT NULL,
                nom_evenement VARCHAR NOT NULL,
                description_evenement VARCHAR NOT NULL,
                nb_participant INTEGER NOT NULL,
                date_evenement DATE NOT NULL,
                CONSTRAINT id_evenement PRIMARY KEY (id_evenement)
);


CREATE INDEX evenement_idx
 ON RWS.evenement
 ( id_evenement ASC );

ALTER TABLE RWS.departement ADD CONSTRAINT pays_departement_fk
FOREIGN KEY (id_pays)
REFERENCES RWS.pays (id_pays)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE RWS.ville ADD CONSTRAINT departement_ville_fk
FOREIGN KEY (id_departement)
REFERENCES RWS.departement (id_departement)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE RWS.evenement ADD CONSTRAINT ville_evenement_fk
FOREIGN KEY (id_ville)
REFERENCES RWS.ville (id_ville)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE RWS.utilisateur ADD CONSTRAINT ville_utilisateur_fk
FOREIGN KEY (id_ville)
REFERENCES RWS.ville (id_ville)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE RWS.evenement ADD CONSTRAINT utilisateur_evenement_fk
FOREIGN KEY (id_ville)
REFERENCES RWS.utilisateur (id_ville)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE RWS.star ADD CONSTRAINT style_musicale_star_fk
FOREIGN KEY (id_style_musical)
REFERENCES RWS.style_musicale (id_style_musical)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE RWS.evenement ADD CONSTRAINT star_evenement_fk
FOREIGN KEY (id_star)
REFERENCES RWS.star (id_star)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;